HuggingFaceH4/no_robots:
  split: train_sft
  text_key: messages
  sample_size: 200
  process: False
  transform_func: None
wikimedia/wikipedia:
  config: 20231101.en
  split: train
  text_key: text
  sample_size: 100
  process: False
  transform_func: None
lukaemon/mmlu:
  split: train
  text_key: text
  sample_size: 10
  process: True
  transform_func: mmlu_converter